spring.application.name=laundryforu

# Pastikan nama database di bawah ini sama dengan yang ada di phpMyAdmin
spring.datasource.url=jdbc:mysql://localhost:3306/laundryforu_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true